[package]
name = "rpm-deps"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
argh = "0.1.12"
petgraph = { version = "0.6.4", default-features = false, features = ["graphmap"] }
rpm = "0.13.1"
